### ISSUE TITLE
Does not change font after reload.

### ISSUE THREAD

**Issue by DanyaalMajid** [animsh/vs-code-custom-ui-font#1]
The font does not change after reload, i have tried multiple fonts, also does not show any warning about corrupted VS Code installation, which seems like it did nothing.

Using VS Code 1.84.2.
If any logs are required, do ask.

**Comment by animsh** [comment]
Can you provide details like what procedure you followed, what was font name and what actual input you gave , remeber it's case sensitive so you have to enter exact name.

**Comment by animsh** [comment]
Extention is updated, Do following steps:

1. Install VS code again even if it's already installed so that configuration will go to default.
2. Run Extension, enter exact name of font you want to have on you VS Code UI, make sure font is present in your system.
