### ISSUE TITLE
Running Change UI font command doesn't change font

### ISSUE THREAD

**Issue by skrewde** [animsh/vs-code-custom-ui-font#2]
As the title indicates, running the extension's command doesn't work.

Tried uninstalling/reinstalling and restarting VS Code, no change.

Extra:
* Tried a similar extension (written by ChatGPT, published by Everything Sucks) called "UI Font Changer" and got this error:
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/f99d5d00-8ea7-436f-8544-14ac286c8c36)
* Changing the UI font through the CSS file works just fine.

**Comment by animsh** [comment]
Try with running as administartor. Can you provide me details like vs code version, windows version and what procedure you followed.

**Comment by animsh** [comment]
Extention is updated, Do following steps:

1. Install VS code again even if it's already installed so that configuration will go to default.
2. Run Extension, enter exact name of font you want to have on you VS Code UI, make sure font is present in your system.

**Comment by skrewde** [comment]
Tried everything you listed above, and I still have the same issue. There is a change though; I now get the corrupt message even without the font change:
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/1e27e2e0-70ae-422f-9232-a2de5380d027)


I'm not sure how effective the uninstall was considering I have Settings sync on though.

**Comment by animsh** [comment]
Maybe it's happeing because the settings of extension being saved in context of extension, I have to find another way to save settings. Let me find another way to save data.

**Comment by skrewde** [comment]
Alright, here's the [thread](https://github.com/everythingsucksass/ui-font-changer/issues/1) for the other extension.

The author mentioned something about Node JS.

**Comment by animsh** [comment]
I have made changes @skrewde , try version 1.0.2, will be live soon on vs code market place, follow below process:

1. Remove previous verison of extension.
2. Reinstall vs code to refresh default configuration files (without this nothing will work, reinstall will not delete your setting or other extension)
3. Install and run Extension, enter exact name of font you want to have on you VS Code UI, make sure font is present in your system. (make sure verison is 1.0.2)

**Comment by skrewde** [comment]
Just reloaded the extension, restarted, and tested the command and it worked:
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/672e0081-a411-4a03-b609-b0243c35b568)

I'll keep an eye on it to see if anything changes. Can I ask what the fix was?

**Comment by skrewde** [comment]
Another font:
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/a9ac766d-f98c-4a0b-8323-51ebd2858e2d)

**Comment by animsh** [comment]
@skrewde well first I was saving user settings in extention context, and somehow things are getting broken because that context wasn't updating properly, also for current version keep in mind that, **If you remove this extension/ remove vs code and install it again then you have to delete file named settings.json which is created by extention, from current user's document folder otherwise it will not update properly.** I will update readme for this.

**Comment by skrewde** [comment]
Hold on...doesn't the setting.json file contain my other settings/customisations as well?

Asides the rendered text on the Marketplace, everything seems fine:
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/2346e8ce-5a13-4ac6-8452-6b51944881c9)

Another font (Product Sans). I think it's OK to close the issue.

**Comment by skrewde** [comment]
Update:
The search bar text also uses Inter.

*Extensions*
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/8bab7554-1c3b-4b21-a3d0-2cb54153674c)

*Settings search*
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/8efeba3c-7d43-4a7f-9fd0-17302d000e34)

*Drop-down list*
![image](https://github.com/animsh/vs-code-custom-ui-font/assets/94148640/b6b8fef6-7824-43db-8500-48b94e0abf8c)


I think this is outside the scope of the original issue so closing is still fine. Just wanted to let you know.

**Comment by animsh** [comment]
No problem, I will look into this.
